### ISSUE TITLE
Add column indicating the source record type where the observation was extracted from

### ISSUE THREAD

**Issue by micmart** [picnichealth/flywheel-data#12]
We will likely have to agree on granularity but categories such as medical history, laboratory test results, diagnostic test results, problem list, clinical notes, treatment notes would be useful.

**Comment by micmart** [comment]
Conditions:
- problem list
- diagnosis list
- global labelling (narrative text)

Measurements:
- lab report
- vital sign sections of visits
- global labelling (narrative text)
  - specific type of report/section/evaluation

Drug (being investigated):
- medication list (most common, specific part of record or paragraph)
- assessment or plan section of visit note (narrative text)

**Comment by micmart** [comment]
Hi @GillianHanson where can I find these columns?

**Comment by GillianHanson** [comment]
Resolved by typeConceptId column

**Comment by micmart** [comment]
![image](https://user-images.githubusercontent.com/29302194/50169274-8d249380-02ed-11e9-86a5-e438a3240fd8.png)
