### ISSUE TITLE
 Access to the unstructured text

### ISSUE THREAD

**Issue by macek2** [picnichealth/flywheel-data#13]
For certain basic applications, a global abstraction may not be necessary, and using an NLP technique may suffice.

Two proposed solutions are:

1.  A "bag of words" style output. With words that do not often show up (like Smith, Jones, etc) omitted
2. Providing the mapped text using a tool such as https://metamap.nlm.nih.gov which anonymized text and maps similar terms to a common vocabulary. 

Initially I feel these would be most useful at a visit level, although much discussion still needs to be had.

**Comment by macek2** [comment]
Is it possible to do a bag of words per visit instead of a single bag of words over the entire database?

**Comment by micmart** [comment]
Not resolved but no longer an issue. Will be reopened if necessary later.
