### ISSUE TITLE
Change specified columns in measurements of type string to json

### ISSUE THREAD

**Issue by GillianHanson** [picnichealth/flywheel-data#15]
For certain columns in the measurements export, the current data type is a mixture of json, number, or string, depending on the specified field type.  We want to change these to all be json, and the json keys are specified by the field type.

For example, in the [measurements](measurements.csv) table:
- now: value currently contains values that are numeric, json, and strings
- after: value will be json and valueType will specify the json keys
   - e.g. valueType = range, value = {"type":"enum","lowValue":numeric,"highValue":numeric,"borderValue":numeric}

Affected columns:
value, referenceRange, sourceValue, sourceReferenceRange

**Comment by GillianHanson** [comment]
valueType = concept: {“conceptId”: UUID}
valueType = range: {“type”: enum, “lowValue”: numeric, “highValue”: numeric, “borderVaue”: numeric}
valueType = ratio: {“numerator”: numeric, “denominator”: numeric}
valueType = ratioRange: {“type”: enum, “lowValue”: numeric, “highValue”: numeric, “borderValue”: {“numerator”:numeric, “denominator”:numeric}}
valueType = number: {“value”:numeric}

referenceRangeType = concept: {“conceptId”: UUID}
referenceRangeType = range: {“type”: enum, “lowValue”: numeric, “highValue”: numeric, “borderVaue”: numeric}
referenceRangeType = ratio: {“numerator”: numeric, “denominator”: numeric}
referenceRangeType = ratioRange: {“type”: enum, “lowValue”: numeric, “highValue”: numeric, “borderValue”: {“numerator”:numeric, “denominator”:numeric}}
referenceRangeType = number: {“value”:numeric}

valueType = concept: {“conceptId”: UUID}
valueType = range: {“type”: enum, “lowValue”: numeric, “highValue”: numeric, “borderVaue”: numeric}
valueType = ratio: {“numerator”: numeric, “denominator”: numeric}
valueType = ratioRange: {“type”: enum, “lowValue”: numeric, “highValue”: numeric, “borderValue”: {“numerator”:numeric, “denominator”:numeric}}
valueType = number: {“value”:numeric}

sourceValueType = string: {"string:" string}
sourceValueType = concept: {“conceptId”: UUID}
sourceValueType = range: {“type”: enum, “lowValue”: numeric, “highValue”: numeric, “borderVaue”: numeric}
sourceValueType = ratio: {“numerator”: numeric, “denominator”: numeric}
sourceValueType = ratioRange: {“type”: enum, “lowValue”: numeric, “highValue”: numeric, “borderValue”: {“numerator”:numeric, “denominator”:numeric}}
sourceValueType = number: {“value”:numeric}

sourceReferenceRangeType = string: {"string:" string}
sourceReferenceRangeType = concept: {“conceptId”: UUID}
sourceReferenceRangeType = range: {“type”: enum, “lowValue”: numeric, “highValue”: numeric, “borderVaue”: numeric}
sourceReferenceRangeType = ratio: {“numerator”: numeric, “denominator”: numeric}
sourceReferenceRangeType = ratioRange: {“type”: enum, “lowValue”: numeric, “highValue”: numeric, “borderValue”: {“numerator”:numeric, “denominator”:numeric}}
sourceReferenceRangeType = number: {“value”:numeric}

**Comment by micmart** [comment]
v1:
![image](https://user-images.githubusercontent.com/29302194/49762844-44f0ea00-fccb-11e8-910e-798bd95e3cdf.png)

v2:
![image](https://user-images.githubusercontent.com/29302194/49762880-605bf500-fccb-11e8-9182-8176ce5b4963.png)
