### ISSUE TITLE
Change unit to unitConceptId in strength column of Drug table

### ISSUE THREAD

**Issue by GillianHanson** [picnichealth/flywheel-data#17]
![image](https://user-images.githubusercontent.com/8450961/48805754-120b9580-eccd-11e8-9c9a-c7a63f7c5944.png)

When complete, update data dictionary to include allowable data type (uuid) and vocabulary (RxNorm).

**Comment by micmart** [comment]
V2 Drug table:
![image](https://user-images.githubusercontent.com/29302194/49763039-da8c7980-fccb-11e8-8deb-51b13ccf7c08.png)
