### ISSUE TITLE
Provide a readable version of tables with conceptIds

### ISSUE THREAD

**Issue by GillianHanson** [picnichealth/flywheel-data#19]
This will not be for analysis, but simply a more human-readable version of the export that currently relies on joining to the concept table to "read" the information.

Example:
Condition
Condition_Readable

**Comment by micmart** [comment]
Actually this seems fine as for e.g. units you pull in the code column from the concept table and not the name column. I was confused as you also named the column unitConceptName and not unitConceptCode in the _readable.csv table.
