### ISSUE TITLE
Include JSON value column in Measurements

### ISSUE THREAD

**Issue by troyastorino** [picnichealth/flywheel-data#2]
Include a JSON column for holding value in the Measurement table, to give a single column for reading a value instead of having to spread across many columns.

**Comment by GillianHanson** [comment]
two columns: (excluding unit conversion aspect)
value (json)
valueType (enum)

**Comment by macek2** [comment]
JSON is not ubiquitous in this column. 

For some measurements the value is a float, others it is JSON.

**Comment by GillianHanson** [comment]
Resolved with [Issue #15:](https://github.com/picnichealth/flywheel-data/issues/15)
