### ISSUE TITLE
Represent date with precision

### ISSUE THREAD

**Issue by GillianHanson** [picnichealth/flywheel-data#5]
**Background:**
- Most dates are stored down to the precision "day," but there are times when either more information is given (e.g. a serial set of vitals performed at distinct intervals with the time of each specified in the record) or less information (e.g. "started Tecfidera in 2017") is reported in the record.

**Goal:** 
- Represent dates in a consistent format but with the appropriate level of precision.

**Proposal:** 
- `startDate` and `endDate` columns of data type `json<date>`
- date value format: 0000-00-00T00:00:00
- Precision can be YEAR, MONTH, DAY, HOUR, or MINUTE.
- When that level of precision is not specified, the value is '00'.

Example 1: A visit occurring on January 1st, 2011.
- `{""type"":""date"", ""date"":{""value"":""2011-01-01T00:00:00"",""precision"":""DAY""}}`

Example 2: A visit occurring on September 3rd, 2015, at 1:20pm
- `{""type"":""date"", ""date"":{""value"":""2015-09-03T13:20:00"",""precision"":""MINUTE""}}`

Example 3: Started Ocrevus in 2017.
- `{""type"":""date"", ""date"":{""value"":""2017-00-00T00:00:00"",""precision"":""YEAR""}}`

Example 4: Tecfidera started 1 year ago and the date of the visit where this is mentioned is August 24th, 2017.
- `{""type"":""date"", ""date"":{""value"":""2017-08-24T00:00:00"",""precision"":""YEAR""}}`

**Comment by micmart** [comment]
I suggest not to nest within json. As you mention that is not human-readable at all.
The default we use is ISO 8601 which means "2011-01-01T13:20:00" for datetime and "2011-01-01" for date. Best would be to stick to date only for all not vitals etc. columns where no time is expected and for the dates where time occurs to use the datetime format.
When e.g. day is missing according to the standard one would use "2011-01" and if month missing also "2011". We then have the issue that some dates can't be read and converted into numerical representation but I guess that would be the same as with "2011-01-00" for missing day and then I would prefer "2011-01" as that more clearly shows that the day part is missing.
Sometimes there are still cases where we would present data snippets using e.g. Excel or in a presentation. Therefore it is still important that the data is human-readable and ideally we use formats which are both machine and human friendly.

**Comment by GillianHanson** [comment]
Decision: two columns
startDate (datetime)
startDatePrecision (enum)
endDate (datetime)
startDatePrecision (enum)

**Comment by GillianHanson** [comment]
Decision: Inpute the middle (when abstract precision)

**Comment by troyastorino** [comment]
Another thing to consider: for imputing middle, do we want to take timezone of visit into account? I think yes.

**Comment by micmart** [comment]
v2 Drug table:
![image](https://user-images.githubusercontent.com/29302194/49763770-e11bf080-fccd-11e8-99e5-2e75cfaaccef.png)
