### ISSUE TITLE
Convert measurements (lab tests) to cleaned values in SI units

### ISSUE THREAD

**Issue by micmart** [picnichealth/flywheel-data#7]
Identical lab test types are currently captured in various units which makes them difficult to analyse and understand. The units and values should therefore be converted to the standard SI unit and captured in columns e.g. UnitCleaned, ResultCleaned.

References:
[Clinical Laboratory Reference Values](https://accessmedicine.mhmedical.com/content.aspx?bookid=1069&sectionid=60775149)
[Position on Use of SI Units for Lab Tests](https://www.fda.gov/downloads/ForIndustry/DataStandards/StudyDataStandards/UCM587505.pdf)

**Comment by GillianHanson** [comment]
Decision: 
unit convert based on standard UCUM suggestion within LOINC
unit convert ref range

**Comment by micmart** [comment]
closed with #19
